### ISSUE TITLE
Because unistd is just a wrapper for syscalls?

### ISSUE THREAD

**Issue by torralbaa** [ia0/stdio-vs-unistd#1]
And `stdio` does lots of operations with pointers and buffers?

~~To be honest, IDK why I opened this issue.~~

**Comment by ia0** [comment]
Yeah, this explains why stdio is slower, but why is it *that* slow :D

But anyway, this is super old :-) How come you ended up here? I forgot this existed.

**Comment by torralbaa** [comment]
> but why is it _that_ slow

No idea :shrug:

> How come you ended up here?

I was just searching about the topic, because I need the speed for some project, and I felt like opening this issue/commenting this xD

**Comment by ia0** [comment]
Hehe fun :-)

**Comment by torralbaa** [comment]
I think this could be closed now...
